### ISSUE TITLE
Alpha roadmap

### ISSUE THREAD

**Issue by vearutop** [vearutop/photo-blog#2]
* [ ] add view stats collector for images, albums
* [x] add photos uploader
* [x] add canon tracks to map in album
* [x] add gpx tracks to map in album
* [ ] add shareable aggregating page to list particular unpublished albums
* [ ] rss to such page ^
* [ ] add masonry renderer to album
* [ ] add optional 2x size to `image_album` 
* [x] improve thumbnailer to use hires thumb to build a lowres thumb
* [x] split main and thumb databases
* [x] add text labels (markdown descriptions) to albums and images
* [x] use hash id in images and albums
* [x] make album names immutable
* [ ] add url shortener (revocable, without explicit redirect to unpublished album, perhaps attached to a cookie)
* [x] add user id cookies
* [ ] add user/password creation
* [x] add github.com/buckket/go-blurhash thumbs
* [ ] poor man's self update with bash loop in screen
* [x] tweak defaults to work without any config
* [x] store/manage config via db
* [x] make album photo permlinks actual links (with redirection to hash anchored link?) and create OG preview page for proper sharing
